[package]
name = "embed_fixer"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
regex = "1.11.3"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
