[package]
name = "embed_fixer"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
regex = "1.11.3"
serenity = "0.12.4"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
