[package]
name = "embed_fixer"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
regex = "1.11"
serenity = "0.12"
tokio = { version = "1.21", features = ["macros", "rt-multi-thread"] }
